### ISSUE TITLE
Escalate privileges with sudo

### ISSUE THREAD

**Issue by gsuyemoto** [kongbytes/arp-scan-rs#4]
Hey! Great project and thanks for all the work! I use the sudo crate for a bunch of my projects and thought it could be useful for this project as well. Just a one-liner and you can provide the user with, IMHO, a nicer experience by being able to upgrade to sudo without having to exit and then rerun the app. I can submit a pull request if needed. Thanks again for the great work!

**Comment by Saluki** [comment]
Hello @gsuyemoto ! Thank you for the feedback :+1: 
Great idea, adding the `sudo` crate could indeed be a nice improvement to the project - do you want to open a PR ?

**Comment by gsuyemoto** [comment]
Hey Corentin,

Sure, I can submit a PR. I haven't submitted a PR to any other project, so
I'm a noob! I have a branch set up with the changes:

   - Added sudo crate to Cargo.toml => sudo = "0.6"
   - Modified main.rs to add sudo call at the very beginning of main()
   - Removed call to function that checks for sudo privileges in main()
   - Removed function for checking sudo privileges in utils.rs
   - Removed use::std::env in utils.rs as the sudo function seemed to be
   the only code needing it

Please let me know if I'm missing anything.
Gary

**Comment by Saluki** [comment]
Thanks for the PR @gsuyemoto - that was fast :+1: I will close this thread and move the discussion to #5 before merging
